version: '3'

services:
  backend:
    container_name: easy-shop-demo-backend
    build: ./backend
    volumes:
      - ./backend/database.json:/app/database.json
    restart: always
    networks:
      - easy-shop-demo-network
    ports:
      - "3001:3000"
  frontend:
    container_name: easy-shop-demo-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components/
      - ./frontend/lib:/app/lib/
      - ./frontend/models:/app/models/
      - ./frontend/public:/app/public/
    restart: always
    networks:
      - easy-shop-demo-network
    ports:
      - "3000:3000"
networks:
  easy-shop-demo-network:
  
